[build]
# Use the faster linker on macOS
[target.aarch64-apple-darwin]
rustflags = ["-C", "link-arg=-fuse-ld=lld"]

[alias]
ck = "check --workspace --all-targets"
t  = "test --workspace"
cl = "clippy --workspace --all-targets -- -D warnings"
